variables:
  MODULE: .

include:
  - project: 'just-ci/templates'
    file: 
      - 'templates/python.yml'
      - 'project-automation/badge.yml'
    ref: 'v5.2.1'

badge:prepare:
  stage: .pre
  image:
    name: alpine/git
    entrypoint: [""]
  script:
    - echo "COMMIT_COUNT=$(git rev-list --all --count)" > badges.env
    - echo "LATEST_TAG=$(git tag | sort -V | tail -1)" >> badges.env
  artifacts:
    reports:
      dotenv: badges.env

.badge:
  dependencies:
    - badge:prepare

badge:commits:
  extends: .badge
  variables:
    LABEL: "commits"
    VALUE: "${COMMIT_COUNT}"
    COLOR: "green"
    URL: "${CI_PROJECT_URL}"

badge:version:
  extends: .badge
  variables:
    LABEL: "version"
    VALUE: "${LATEST_TAG}"
    COLOR: "blue"
    URL: "${CI_PROJECT_URL}"

badge:license:
  extends: .badge
  variables:
    LABEL: "license"
    VALUE: "MPL-2.0"
    COLOR: "orange"
    URL: "${CI_PROJECT_URL}"

badge:code-style:
  extends: .badge
  variables:
    LABEL: "code-style"
    VALUE: "black"
    COLOR: "black"
    URL: "${CI_PROJECT_URL}"
